# Global state constants for the bot conversation handler
UPLOAD = 0
ACTION = 1
MANUSCRIPT_REVIEW = 2
VISUAL_SELECT = 3
SAVE_PROJECT = 4

# Interview states
RESEARCH_TITLE = 10
RESEARCH_OBJECTIVES = 11
RESEARCH_QUESTIONS = 12
RESEARCH_HYPOTHESIS = 13
GOAL_SELECT = 14
VAR_SELECT_1 = 15
VAR_SELECT_2 = 16
CONFIRM_ANALYSIS = 17
POST_ANALYSIS = 18

# Sampling states
MODE_SELECT = 30
STUDY_TYPE_SELECT = 31
POPULATION_CHECK = 32
METHOD_SELECT = 33
CI_SELECT = 34
PARAM_INPUT = 35

# Signup states
S_ID = 49
S_NAME = 50
S_EMAIL = 51
S_PHONE = 52
S_COUNTRY = 53

# Analysis states
TEST_SELECT = 70
VAR_SELECT_GROUP = 71
VAR_SELECT_TEST = 72
ANOVA_SELECT_FACTOR = 73
ANOVA_SELECT_DV = 74
RELIABILITY_SELECT = 75
GUIDE_CONFIRM = 76
